name: flutter CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - name:  Checkout code
              uses: actions/checkout@v3

            - name: set up flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: 3.29.0

            - name: Install dependencies
              run:  flutter pub get
          
            - name: Project analyze
              run: flutter analyze
          
            - name: Run tests
              run: flutter test 
              
            - name: Build Apk
              run: flutter build apk --release

            - name: Upload APK artifacts
              run: actions/upload-artifacts@v4
              
            - name: relese-apk
              run: build/apps/outputs/flutter-apk/app-relese.apk  




    