name: flutter CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - name:  Checkout code
              uses: actions/checkout@v3

            - name: set up flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: 3.29.0

            - name: Cache flutter depencies
              uses: actions/checkout@v2
              with:
                path: |
                  ~/.pub-cache
                  ~/.gradle 
                key: $ {{runner.os}}-flutter-$ {{ hashFiles('**/punspec.yaml') }}   
                restore-keys: |
                  $ {{ runner.os}}-flutter-

            - name: Install dependencies
              run:  flutter pub get

            - name: Format Check
              run: dart format --set-exit-if-changed .  
          
            - name: Project analyze
              run: flutter analyze
              

            




    